apiVersion: "v1"
kind: "Template"
metadata:
  name: logging-fluentd-template
  annotations:
    description: "Template for logging fluentd pod - use yaml output from `oc process` as static pod on each node."
    tags: "infrastructure"
labels:
  logging-infra: fluentd
  provider: openshift
  component: fluentd
objects:
-
  apiVersion: v1
  kind: Pod
  metadata:
    name: fluentd-elasticsearch
  spec:
    serviceAccount: aggregated-logging
    containers:
    - name: fluentd-elasticsearch
      image: sosiouxme/fluentd:v0.1
      securityContext:
        privileged: true
      resources:
        limits:
          cpu: 100m
      volumeMounts:
      - name: varlog
        mountPath: /var/log
      - name: varlibdockercontainers
        mountPath: /var/lib/docker/containers
        readOnly: true
      - name: certs
        mountPath: /etc/fluent/keys
        readOnly: true
      env:
      - name: "ES_HOST"
        value: ${ES_HOST}
      - name: "ES_PORT"
        value: "9200"
      - name: "K8S_HOST_URL"
        value: ${MASTER_URL}
    volumes:
    - name: varlog
      hostPath:
        path: /var/log
    - name: varlibdockercontainers
      hostPath:
        path: /var/lib/docker/containers
    - name: certs
      secret:
        secretName: fluentd
parameters:
-
  description: "Internal url for reaching the master API to query pod labels"
  name: MASTER_URL
  value: "https://kubernetes.default.svc.cluster.local:8443"
-
  description: "Hostname (or IP) for reaching ElasticSearch to write logs"
  name: ES_HOST
  value: "es-logging"
