apiVersion: "v1"
kind: "Template"
metadata:
  name: logging-kibana-template
  annotations:
    description: "Template for deploying log viewer Kibana connecting to ElasticSearch to visualize aggregated cluster logs."
    tags: "infrastructure"
labels:
  logging-infra: kibana
  provider: openshift
  component: kibana
objects:
-
  apiVersion: "v1"
  kind: "DeploymentConfig"
  metadata:
    name: "kibana"
    labels:
      provider: openshift
      component: "kibana"
  spec:
    replicas: 1
    selector:
      provider: openshift
      component: "kibana"
    triggers:
    - type: ConfigChange
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        name: "kibana"
        labels:
          provider: openshift
          component: "kibana"
      spec:
        serviceAccount: aggregated-logging
        containers:
          -
            name: "kibana"
            image: "sosiouxme/openshift-kibana:v0.1"
            ports:
              -
                name: "kibana-port"
                containerPort: 5601
            env:
              - name: "ES_HOST"
                value: ${ES_HOST}
              - name: "ES_PORT"
                value: ${ES_PORT}
            volumeMounts:
              - name: kibana
                mountPath: /etc/kibana/keys
                readOnly: true
          -
            name: "kibana-proxy"
            image: "sosiouxme/openshift-auth-proxy:v0.1"
            ports:
              -
                name: "oaproxy"
                containerPort: 3000
            env:
              -
                name: "OAP_BACKEND_URL"
                value: "http://localhost:80"
              -
                name: "OAP_AUTH_MODE"
                value: "oauth2"
              -
                name: "OAP_TRANSFORM"
                value: "user_header"
              -
                name: "OAP_OAUTH_ID"
                value: kibana-proxy
              -
                name: "OAP_MASTER_URL"
                value: ${OAP_MASTER_URL}
              -
                name: "OAP_PUBLIC_MASTER_URL"
                value: ${OAP_PUBLIC_MASTER_URL}
              -
                name: "OAP_MASTER_CA_FILE"
                value: "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
              -
                name: "OAP_DEBUG"
                value: ${OAP_DEBUG}
            volumeMounts:
              - name: kibana-proxy
                mountPath: /secret
                readOnly: true
        volumes:
          - name: kibana
            secret:
              secretName: kibana
          - name: kibana-proxy
            secret:
              secretName: kibana-proxy
parameters:
-
  description: "Internal URL for the master, for authentication retrieval"
  name: OAP_MASTER_URL
  value: "https://kubernetes.default.svc.cluster.local:8443"
-
  description: "Public URL for the master, for sending the browser to authenticate"
  name: OAP_PUBLIC_MASTER_URL
  required: true
-
  description: "Hostname/IP for ElasticSearch backend to connect to."
  name: ES_HOST
  value: es-logging
-
  description: "Port to connect to for ElasticSearch backend."
  name: ES_PORT
  value: "9200"
-
  description: "Show extra proxy debug information at startup and during operations"
  name: OAP_DEBUG
  value: "false"
